name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Select Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy_infra:
    name: Deploy AWS Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/TerraformGithubActionsRole
          role-session-name: github-actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform fmt check
        working-directory: .
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: .
        run: terraform validate

      - name: Terraform init
        working-directory: .
        run: terraform init

      - name: Terraform plan
        working-directory: dev
        run: terraform plan

      - name: Terraform apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        working-directory: dev
        run: terraform apply -auto-approve

      - name: Terraform destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        working-directory: dev
        run: terraform destroy -auto-approve
