name: Deploy Infrastructure

on:
 workflow_dispatch:
   inputs:
     terraform_action:
       type: choice
       description: select terraform action
       options:
       - apply
       - destroy
       required: true

 push:
   branches:
     - main

permissions:
 contents: read
 id-token: write

jobs:
  deploy_infra:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/TerraformGithubActionsRole
          role-session-name: github-actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform Init
        working-directory: environment/dev
        run: terraform init -reconfigure

      - name: Terraform Plan
        working-directory: environment/dev
        run: terraform plan 

      
      - name: Terraform apply or Destroy
        working-directory: environment/dev
        run: |
          if [ "${{ github.event.inputs.terraform_action }}" == "apply" ]; then
            terraform plan -out=tfplan
            terraform apply tfplan
          else
            terraform destroy -auto-approve
          fi
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }} 
          TF_VAR_Admin_CIDR: ${{ secrets.ADMIN_CIDR }}
#.